KTRA/Models/TacGia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public TacGia()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaTacGia { get; set; }
        public string TenTacGia { get; set; }
    
        public virtual ICollection<Sach> Saches { get; set; }
    }
}

KTRA/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KTRA.Models;

namespace KTRA.Controllers
{
    public class SachController : Controller
    {
        THDAPMEntities db = new THDAPMEntities();
        
        // GET: Sach
        public ActionResult Index()
        {
            var dsSach = db.Saches.OrderByDescending(s => s.TenSach).ToList();
            return View(dsSach);
        }
        
        public ActionResult SachTheoTacGia(int id)
        {
            return View("Index", db.Saches.Where(tg => tg.MaTacGia == id).ToList());
        }
        // GET: Sach/Details/5
        public ActionResult Details(int id)
        {
            return View(db.Saches.Where(s => s.MaSach == id).FirstOrDefault());
        }

        // GET: Sach/Create
        public ActionResult Create()
        {
            ViewBag.MaTacGia = new SelectList(db.TacGias, "MaTacGia", "TenTacGia");
            return View();
        }

        // POST: Sach/Create
        [HttpPost]
        public ActionResult Create(Sach sach)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(sach.TenSach))
                    ModelState.AddModelError(string.Empty, "Tên sach không được để trống");
                if (ModelState.IsValid)
                {
                    db.Saches.Add(sach);
                    db.SaveChanges();
                    return Redirect("/Sach/Index");
                }
            }
            ViewBag.MaTacGia = new SelectList(db.TacGias, "MaTacGia", "TenTacGia", sach.MaTacGia);
            return View();
        }

        // GET: Sach/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTacGia = new SelectList(db.TacGias, "MaTacGia", "TenTacGia", sach.MaTacGia);
            return View(sach);
        }

        // POST: Sach/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Sach sach)
        {
            if (ModelState.IsValid)
            {
                var sanPhamDB = db.Saches.FirstOrDefault(kh => kh.MaSach == sach.MaSach);
                if (sanPhamDB != null)
                {
                    sanPhamDB.TenSach = sach.TenSach;
                    sanPhamDB.DonGia = sach.DonGia;
                    sanPhamDB.MaTacGia = sach.MaTacGia;
                }
                db.SaveChanges();
                return Redirect("/Sach/Index");
            }
            ViewBag.MaTacGia = new SelectList(db.TacGias, "MaTacGia", "TenTacGia", sach.MaTacGia);
            return View(sach);
        }

        // GET: Sach/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Sach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sach sach = db.Saches.Find(id);
            db.Saches.Remove(sach);
            db.SaveChanges();
            return Redirect("/Sach/Index");
        }
    }
}

KTRA/Controllers/TacGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KTRA.Models;

namespace KTRA.Controllers
{
    public class TacGiaController : Controller
    {

        THDAPMEntities db = new THDAPMEntities();

        // GET: Sach
        public ActionResult Index()
        {
            var dsTacGia = db.TacGias.OrderByDescending(s => s.TenTacGia).ToList();
            return View(dsTacGia);
        }

        public ActionResult Shop()
        {
            var dsSach = db.Saches.OrderByDescending(s => s.TenSach).ToList();
            return View(dsSach);
        }

        public ActionResult PartialTacGia()
        {
            return PartialView(db.TacGias.OrderByDescending(tg => tg.TenTacGia).ToList());
        }

        // GET: Sach/Details/5
        public ActionResult Details(int id)
        {
            return View(db.TacGias.Where(s => s.MaTacGia == id).FirstOrDefault());
        }

        // GET: Sach/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sach/Create
        [HttpPost]
        public ActionResult Create(TacGia tg)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(tg.TenTacGia))
                    ModelState.AddModelError(string.Empty, "Tên sach không được để trống");
                if (ModelState.IsValid)
                {
                    db.TacGias.Add(tg);
                    db.SaveChanges();
                    return Redirect("/TacGia/Index");
                }
            }
            return View();
        }

        // GET: Sach/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sach = db.TacGias.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Sach/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TacGia tg)
        {
            if (ModelState.IsValid)
            {
                var sanPhamDB = db.TacGias.FirstOrDefault(kh => kh.MaTacGia == tg.MaTacGia);
                if (sanPhamDB != null)
                {
                    sanPhamDB.TenTacGia = tg.TenTacGia;
                }
                db.SaveChanges();
                return Redirect("/TacGia/Index");
            }
            return View(tg);
        }

        // GET: Sach/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sach = db.TacGias.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Sach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TacGia tg = db.TacGias.Find(id);
            db.TacGias.Remove(tg);
            db.SaveChanges();
            return Redirect("/Sach/Index");
        }
    }
}

KTRA/Views/TacGia/Create.cshtml
@model KTRA.Models.TacGia

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "TacGia", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TacGia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.TenTacGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KTRA/Views/TacGia/Delete.cshtml
@model KTRA.Models.TacGia

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TacGia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaTacGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTacGia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KTRA/Views/TacGia/Details.cshtml
@model KTRA.Models.TacGia

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TacGia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaTacGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTacGia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KTRA/Views/TacGia/Edit.cshtml
@model KTRA.Models.TacGia

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "TacGia", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TacGia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.MaTacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaTacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenTacGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KTRA/Views/TacGia/Index.cshtml
@model IEnumerable<KTRA.Models.TacGia>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaTacGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenTacGia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaTacGia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenTacGia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaTacGia }) |
            @Html.ActionLink("Details", "Details", new { id = item.MaTacGia }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.MaTacGia })
        </td>
    </tr>
}

</table>

KTRA/Views/TacGia/PartialTacGia.cshtml
@model IEnumerable<KTRA.Models.TacGia>

<div class="title">Tac Gia</div>
<ul class="list-group">
    @foreach (var tg in Model)
    {
        <a href="@Url.Action("SachTheoTacGia", "Sach", new { id=tg.MaTacGia })"
           class="list-group-item list-group-item-action">
            @tg.TenTacGia
        </a>
    }
</ul>

KTRA/Views/TacGia/Shop.cshtml
@model IEnumerable<KTRA.Models.Sach>

@{
    ViewBag.Title = "Shop";
    Layout = "~/Views/Shared/_LayoutShop.cshtml";
}

<h2>Shop</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaTacGia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonGia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaTacGia)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>